=== KollarMaTT/J004TM_XMLGyak/J004TM_1005/KM_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/KM_konyv" elementFormDefault="qualified">


<xs:element name="konyvek">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="konyv" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="cim" type="xs:string"/>
						<xs:element name="kiadas" type="xs:unsignedShort"/>
						<xs:element name="kiado" type="xs:string"/>
						<xs:element name="szerzo" type="xs:string" maxOccurs="unbounded"/>
						<xs:element name="abstract" type="xs:string"/>
					</xs:sequence>
					<xs:attribute name="kod" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== KollarMaTT/J004TM_XMLGyak/J004TM_1005/KM_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>


<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="KM_konyv.xsd">
	<konyv kod="h1">
		<cim>Bevezetés az informatikába</cim>
		<kiadas>2007</kiadas>
		<kiado>Libri</kiado>
		<szerzo>Tóth Ottó</szerzo>
		<abstract>Random</abstract>
	</konyv>
	<konyv kod="h2">
		<cim>A JavaScript alapjai</cim>
		<kiadas>2015</kiadas>
		<kiado>Libri</kiado>
		<szerzo>Havas Henrik</szerzo>
		<szerzo>Tóth Ottó</szerzo>
		<abstract>Random</abstract>
	</konyv>
	<konyv kod="h3">
		<cim>A JavaScript alapjai</cim>
		<kiadas>2015</kiadas>
		<kiado>Libri</kiado>
		<szerzo>Havas Henrik</szerzo>
		<abstract>Random</abstract>
	</konyv>
</konyvek>
