=== KollarMaTT/J004TM_XMLGyak/XMLTaskJ004TM/DOMParseJ004TM/src/XMLSchemaJ004TM.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/XMLJ004TM" 
elementFormDefault="qualified">


	<!-- Felepites -->
	<xs:element name="vendeglatas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="etterem" type="etterem_tipus" maxOccurs="unbounded"/>
				<xs:element name="foszakacs" type="foszakacs_tipus" maxOccurs="unbounded"/>
				<xs:element name="szakacs" type="szakacs_tipus" maxOccurs="unbounded"/>
				<xs:element name="gyakornok" type="gyakornok_tipus" maxOccurs="unbounded"/>
				<xs:element name="vendeg" type="vendeg_tipus" maxOccurs="unbounded"/>
				<xs:element name="rendeles" type="rendeles_tipus" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		
		
		<!-- Kulcsok -->
		<xs:key name="etterem_kulcs">
			 <xs:selector xpath="etterem" /> 
			 <xs:field xpath="@ekod" /> 
		</xs:key>
	
		<xs:key name="foszakacs_kulcs">
			 <xs:selector xpath="foszakacs" /> 
			 <xs:field xpath="@fkod" /> 
		</xs:key>
	
		<xs:key name="szakacs_kulcs">
			 <xs:selector xpath="szakacs" /> 
			 <xs:field xpath="@szkod" /> 
		</xs:key>
	
		<xs:key name="gyakornok_kulcs">
			 <xs:selector xpath="gyakornok" /> 
			 <xs:field xpath="@gykod" /> 
		</xs:key>
	
		<xs:key name="vendeg_kulcs">
			 <xs:selector xpath="vendeg" /> 
			 <xs:field xpath="@vkod" /> 
		</xs:key>
		
		
		<!-- Idegen kulcsok -->
		<xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
			<xs:selector xpath="rendeles" />
			<xs:field xpath="@e_v_e" />
		</xs:keyref>
		<xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
			<xs:selector xpath="rendeles" />
			<xs:field xpath="@e_v_v" />
		</xs:keyref>
		
		<xs:keyref refer="etterem_kulcs" name="etterem_foszakacs_idegen_kulcs">
			<xs:selector xpath="foszakacs" />
			<xs:field xpath="@e_f" />
		</xs:keyref>
		
		<xs:keyref refer="etterem_kulcs" name="etterem_szakacs_idegen_kulcs">
			<xs:selector xpath="szakacs" />
			<xs:field xpath="@e_sz" />
		</xs:keyref>
		
		<xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_idegen_kulcs">
			<xs:selector xpath="gyakornok" />
			<xs:field xpath="@e_gy" />
		</xs:keyref>
		
		
		<!-- Az 1:1 kapcsolat megvalósításához -->
		<xs:unique name="unique_foszakacs">
			<xs:selector xpath="foszakacs"/>
			<xs:field xpath="@e_f"/>
		</xs:unique>
		
	</xs:element>
	
	
	<!-- Tipusok -->
	<xs:complexType name="etterem_tipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="cim" type="cim_tipus"/>
			<xs:element name="csillag" type="xs:integer"/>
		</xs:sequence>
		<xs:attribute name="ekod" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="cim_tipus">
		<xs:sequence>
			<xs:element name="varos" type="xs:string"/>
			<xs:element name="utca" type="xs:string"/>
			<xs:element name="hazszam" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="foszakacs_tipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="eletkor" type="xs:integer"/>
			<xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="fkod" type="xs:string" use="required"/>
		<xs:attribute name="e_f" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="szakacs_tipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="reszleg" type="xs:string"/>
			<xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="szkod" type="xs:string" use="required"/>
		<xs:attribute name="e_sz" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="gyakornok_tipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="gyakorlat" type="gyakorlat_tipus"/>
			<xs:element name="muszak" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="gykod" type="xs:string" use="required"/>
		<xs:attribute name="e_gy" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="gyakorlat_tipus">
		<xs:sequence>
			<xs:element name="kezdete" type="xs:string"/>
			<xs:element name="idotartama" type="xs:string"/>
 		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="vendeg_tipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="eletkor" type="xs:integer"/>
			<xs:element name="cim" type="cim_tipus"/>
		</xs:sequence>
		<xs:attribute name="vkod" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="rendeles_tipus">
		<xs:sequence>
			<xs:element name="osszeg" type="xs:integer"/>
			<xs:element name="etel" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="e_v_e" type="xs:string" use="required"/>
		<xs:attribute name="e_v_v" type="xs:string" use="required"/>
	</xs:complexType>
	
</xs:schema>

=== KollarMaTT/J004TM_XMLGyak/XMLTaskJ004TM/DOMParseJ004TM/src/XMLJ004TM.xml
<?xml version="1.0" encoding="UTF-8"?>

<vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaJ004TM.xsd">


	<!-- Ettermek -->
	<etterem ekod="e1">
		<nev>Tapassio</nev>
		<cim>
			<varos>Budapest</varos>
			<utca>Hercegprímás</utca>
			<hazszam>13</hazszam>
		</cim>
		<csillag>5</csillag>
	</etterem>
	
	<etterem ekod="e2">
		<nev>Arany Kaviár</nev>
		<cim>
			<varos>Budapest</varos>
			<utca>Ostrom</utca>
			<hazszam>19</hazszam>
		</cim>
		<csillag>5</csillag>
	</etterem>
	
	
	<!-- Foszakacsok -->
	<foszakacs fkod="f1" e_f="e1">
		<nev>Havas Henrik</nev>
		<eletkor>45</eletkor>
		<vegzettseg>Szakközépiskola</vegzettseg>
		<vegzettseg>Institut Paul Bocuse</vegzettseg>
	</foszakacs>
	
	<foszakacs fkod="f2" e_f="e2">
		<nev>Nagy Dániel</nev>
		<eletkor>30</eletkor>
		<vegzettseg>Le Cordon Bleu</vegzettseg>
	</foszakacs>
	
	
	<!-- Szakacsok -->
	<szakacs szkod="sz1" e_sz="e1">
		<nev>Ötlet Elek</nev>
		<reszleg>Saucier</reszleg>
		<vegzettseg>Szakközépiskola</vegzettseg>
		<vegzettseg>Le Cordon Bleu</vegzettseg>
		<vegzettseg>Institut Paul Bocuse</vegzettseg>
	</szakacs>
	
	<szakacs szkod="sz2" e_sz="e2">
		<nev>Kocsis Tibor</nev>
		<reszleg>Entremetier</reszleg>
		<vegzettseg>Szakközépiskola</vegzettseg>
		<vegzettseg>Le Cordon Bleu</vegzettseg>
	</szakacs>
	
	<szakacs szkod="sz3" e_sz="e2">
		<nev>Tálas Levente</nev>
		<reszleg>Gardemanger</reszleg>
		<vegzettseg>Szakközépiskola</vegzettseg>
	</szakacs>
	
	<szakacs szkod="sz4" e_sz="e1">
		<nev>Szűcs Judit</nev>
		<reszleg>Entremetier</reszleg>
		<vegzettseg>Le Cordon Bleu</vegzettseg>
		<vegzettseg>Institut Paul Bocuse</vegzettseg>
	</szakacs>
	
	
	<!-- Gyakornokok -->
	<gyakornok gykod="gy1" e_gy="e1">
		<nev>Bordás Dávid</nev>
		<gyakorlat>
			<kezdete>2021.08.20.</kezdete>
			<idotartama>2 hónap</idotartama>
		</gyakorlat>
		<muszak>Délelőtt</muszak>
		<muszak>Este</muszak>
	</gyakornok>
	
	<gyakornok gykod="gy2" e_gy="e2">
		<nev>Szilágyi Marcell</nev>
		<gyakorlat>
			<kezdete>2021.06.01.</kezdete>
			<idotartama>4 hónap</idotartama>
		</gyakorlat>
		<muszak>Délután</muszak>
	</gyakornok>
	
	<gyakornok gykod="gy3" e_gy="e1">
		<nev>Szentpétery Mózes</nev>
		<gyakorlat>
			<kezdete>2021.01.01.</kezdete>
			<idotartama>10 hónap</idotartama>
		</gyakorlat>
		<muszak>Délelőtt</muszak>
		<muszak>Délután</muszak>
	</gyakornok>
	
	
	<!-- Vendegek -->
	<vendeg vkod="v1">
		<nev>Kollár Máté</nev>
		<eletkor>21</eletkor>
		<cim>
			<varos>Arnót</varos>
			<utca>Pázsit</utca>
			<hazszam>74</hazszam>
		</cim>
	</vendeg>
	
	<vendeg vkod="v2">
		<nev>Szentpétery Áron</nev>
		<eletkor>15</eletkor>
		<cim>
			<varos>Miskolc</varos>
			<utca>Örs</utca>
			<hazszam>24</hazszam>
		</cim>
	</vendeg>
	
	<vendeg vkod="v3">
		<nev>Elon Musk</nev>
		<eletkor>26</eletkor>
		<cim>
			<varos>Miskolc</varos>
			<utca>Szilvás</utca>
			<hazszam>4</hazszam>
		</cim>
	</vendeg>
	
	<!-- Rendelesek -->
	<rendeles e_v_e="e1" e_v_v="v1">
		<osszeg>9000</osszeg>
		<etel>Steak</etel>
	</rendeles>
	
	<rendeles e_v_e="e2" e_v_v="v2">
		<osszeg>8000</osszeg>
		<etel>Kaviár</etel>
	</rendeles>
	
	<rendeles e_v_e="e1" e_v_v="v3">
		<osszeg>20000</osszeg>
		<etel>Zsíros kenyér</etel>
	</rendeles>
	
	<rendeles e_v_e="e2" e_v_v="v3">
		<osszeg>300</osszeg>
		<etel>Mackó sajt</etel>
	</rendeles>
	
</vendeglatas>
